version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: pgr
      POSTGRES_PASSWORD: Z168f1218747ed5c7b6e7ab68f37556899ad0c0a5
      POSTGRES_DB: stackframe
    ports:
      - "5432:5432"
    restart: unless-stopped
  stack-auth:
    image: stackauth/server:latest
    container_name: stack-auth
    env_file:
      - ./env-01
    ports:
      - "8101:8101"
      - "8102:8102"
    depends_on:
      - db
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Needed for Linux users
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dave@bxg.ie
      PGADMIN_DEFAULT_PASSWORD: Z168
    ports:
      - "8117:80"
    depends_on:
      - db
    restart: unless-stopped
